### ISSUE TITLE
data timestamps are no longer chronological

### ISSUE THREAD

**Issue by thethereza** [sparkfun/phant#172] opened 2015-11-16 20:59 UTC
if you look at https://data.sparkfun.com/streams/mKwEEDbYX6c4gNnombKL
you'll see that the time in seconds jump around and are not chronological.  this can be visualized here
http://reza.net/kitchen.html

**Comment by datacute** [comment] 2015-11-17 07:58
I've been experiencing the same thing, with a device reporting every 30 seconds (plus about 0.18 seconds to connect and post).
https://data.sparkfun.com/streams/7JxJ1o039miyrl58703v
Graphing the date reported in the server responses, I've drawn the conclusion that there are at least three different servers handling the requests, with three different clocks, and relative to the earliest clock, the other two clocks are about 30 and 41 seconds later, and that each server's clock's timestamp is recorded with the data.

I also suspect that the shifting clocks are playing havoc with the rate limiter. I'm posting 30 times in 15 minutes, so well within the 100 limit, but after a number of hours my device falls into a pattern of 6, 11, 15, and 20 minute delays every hour and a quarter. (I haven't ruled out my code for that yet though.)

**Comment by mperignon** [comment] 2015-11-24 18:09
I may be having a similar issue with an ESP8266 posting to data.sparkfun.com. Timestamps that are not chronological, delays between posts that are very far off the supposed 30 seconds, and delays where the sensor keeps collecting data (increasing a counter) but they don't get posted. Using internet connection sharing is making it worse -- maybe it's adding one more unsynchronized clock to the mix. Have you tried changing the post rate? It would be interesting to see how the delay pattern changes with half or twice the post rate.

**Comment by datacute** [comment] 2015-11-27 01:54
I found two solutions to my pattern of delays, one was to reset the esp8266 whenever the uptime reached one hour. The second was to restart the esp8266 wifi when the connection to data.sparkfun.com failed. These show that the problem is likely in the esp8266.

The problem of the timestamps jumping around remains.

**Comment by DrBit** [comment] 2015-11-30 11:25
I'm also experiencing the same issue. I'm runing the example code for arduino.
https://data.sparkfun.com/streams/xRvJ0wRd5qCQVpD5LdV0

**Comment by mperignon** [comment] 2015-11-30 18:27
I think I found the problem with my setup. I was using the example code for [posting to phant with the ESP8266] (https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/example-sketch-posting-to-phant). Like @datacute, the gaps in my data had a pattern, stopping every 40 minutes for 20 minutes. The data also had funky timestamps, with posts that were seemingly out of order and post spacings (according to the timestamps) that were as little as 9 seconds apart (instead of 30 seconds). I added a post counter to the data stream that increased by one every time `postToPhant()` was called and found that, during the gaps, the post counter jumped by an order of magnitude more than it should have had it been posting every 30 seconds.

I think this was the problem: Starting in line 40 of the example code, `loop()` calls `postToPhant()` and increases the timer `lastPost` by `postRate` if successful or `delay(100)` if not. That means that, if posting fails, the ESP8266 will try to post again in 100 milliseconds and keep trying 10 times a second until it manages to post. If data.sparkfun.com is counting failed attempts towards the 100 post/15 minute cap, it would take as little as 10 seconds of bad connection to reach the limit, locking you out of the data stream for some time.

My solution was to increase the delay in `loop()` to 5000 milliseconds (5 seconds) in order to give the connection time to fix itself before trying to post again. I don't know why it sometimes can't post, but that was enough to avoid hitting the rate limit. If this hadn't fixed the problem, I would have removed the If loop in `loop()` so that the code increases `lastPost` by `postRate` after calling `postToPhant()` regardless of whether posting succeeds. I'd lose the data point but it would forcefully throttle the posting rate.

As for the bad timestamps, I added a [RTC module] (https://www.sparkfun.com/products/12708?gclid=CLKJ-bzfuMkCFZWCaQodM_UFog) to the Thing to post an independent timestamp along with the data. There is definitely variability between the RTC time and the server time but I have not looked for a pattern yet.

@DrBit, hope this helps!

**Comment by mperignon** [comment] 2015-11-30 18:29
Of course, as I wrote this, the Thing stopped posting for the first time in five days. @datacute, how are you resetting the ESP8266?

**Comment by DrBit** [comment] 2015-12-03 01:34
Thanks @mperignon for your input but my code is taken from https://github.com/Serasidis/SparkfunDataClient/blob/master/SparkfunDataClient.ino i doesn't look like it contains the same issue you describe. I'm posting the same data in both sparkfun and thingspeak and they look good in thingspeak.
here my code: https://github.com/DrBit/arduino_energy_monitor/blob/master/energy_monitor.ino

**Comment by thethereza** [comment] 2015-12-03 03:07
Is anyone from spark fun looking at these bug reports?  Should I just migrate to thing speak?

**Comment by ToniCorinne** [comment] 2015-12-03 16:33
Hey there - SparkFun employee here. We are actually in the process of getting a new developer up to speed with phant. Apologies that it's taking a while- there's several large code projects in the work here on our backend, so this is going slower than expected.

**Comment by mperignon** [comment] 2015-12-03 17:55
@DrBit, yep, I couldn't find a similar issue to mine in your code. The fact that you are posting to ThingSpeak without trouble is illuminating.

Thanks for the info, @ToniCorinne . Hopefully it'll get sorted out soon.

**Comment by ShawnHymel** [comment] 2015-12-04 17:38
I've also noticed this issue. I've also added a separate timestamp field to my logs in order to compare it to the server-created timestamp. Every now and then, one of the server timestamps is off, as in, it thinks it's a few seconds in the future. I've added a screenshot - hope this helps!
![datadotsparkfun_error](https://cloud.githubusercontent.com/assets/5232145/11596582/212f7482-9a73-11e5-9322-8c13d391f897.png)

**Comment by thethereza** [comment] 2015-12-04 19:23
Spark fun, if you describe your infrastructure I'll tell you what's wrong and how to fix it.

**Comment by datacute** [comment] 2015-12-05 07:17
My guess is still that SparkFun is running multiple servers to receive the data, and that their clocks are not in sync.

**Comment by zinefer** [comment] 2015-12-06 03:49
This should be fixed. Thanks for the reports!

**Closed by zinefer** 2015-12-06 03:49 UTC

**Comment by DrBit** [comment] 2015-12-06 10:46
confirmed! IT does work for me.
